# Generated by Django 5.1.6 on 2025-03-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited'),
        ),
    ]
